Enable the migration of 3 wmma API
oneapi-src/SYCLomatic pull request #1081
Opened 2023-07-11 08:57 UTC by wenhuiNi

`nvcuda::wmma::load_matrix_sync`, `nvcuda::wmma::mma_sync`, `nvcuda::wmma::store_matrix_sync`

2023-07-13 05:40 UTC, yihanwg commented on clang/lib/DPCT/WMMAAPIMigration.cpp
> +    DRE->dump();
Let's remove this debug dump

2023-07-13 05:41 UTC, yihanwg commented on clang/lib/DPCT/MapNames.cpp
> +            getClNamespace() + "ext::oneapi::experimental::matrix::layout::row_major")},
Do we need add a new option? this seems is a extension

2023-07-13 05:44 UTC, yihanwg commented on clang/lib/DPCT/WMMAAPIMigration.cpp
> +  }else {
Let's format the commit with `git-clang-format HEAD~1`

2023-07-13 05:47 UTC, tangjj11 approved these changes

2023-07-13 05:47 UTC, tangjj11 commented on clang/lib/DPCT/ExprAnalysis.cpp
> -
why modify this file

2023-07-13 05:52 UTC, yihanwg requested changes
Basically LGTM % comments

2023-07-17 08:24 UTC, yihanwg approved these changes
LGTM

2023-07-17 08:53 UTC, AndyCHHuang approved these changes

2023-07-17 08:53 UTC, AndyCHHuang commented on clang/lib/DPCT/CallExprRewriterWmma.cpp
> +  if (DpctGlobalInfo::useExtJointMatrix()) {
Add a comment to explain which funciton migration requires the enum and why we cannot init it when construct EnumNamesMap?

2023-07-19 03:19 UTC, ziranzha approved these changes

2023-07-19 03:20 UTC, merged