[NFC][SYCLomatic] Clean build warnings
oneapi-src/SYCLomatic pull request #1086
Opened 2023-07-12 06:52 UTC by yihanwg

Signed-off-by: Wang, Yihan [yihan.wang@intel.com](mailto:yihan.wang@intel.com)

2023-07-13 01:24 UTC, wenhuiNi approved these changes

2023-07-13 01:27 UTC, tangjj11 requested changes

2023-07-13 01:27 UTC, tangjj11 commented on clang/lib/DPCT/ASTTraversal.cpp
> +      auto Action = [LocInfo]() {
Why pass the `LocInfo` var.

2023-07-13 01:28 UTC, tangjj11 approved these changes

2023-07-13 02:05 UTC, yihanwg commented on clang/lib/DPCT/ASTTraversal.cpp
> +      auto Action = [LocInfo]() {
removed

2023-07-17 09:14 UTC, zhimingwang36 approved these changes
LGTM

2023-07-17 09:14 UTC, merged