Only performed add-inline optimization when the function has no other decl
oneapi-src/SYCLomatic pull request #1103
Opened 2023-07-19 07:45 UTC by wenhuiNi

2023-07-19 07:53 UTC, tangjj11 approved these changes

2023-07-19 07:53 UTC, tangjj11 commented on clang/lib/DPCT/Utility.cpp
> +bool isFuncdeclDefTogether(const clang::FunctionDecl *FD) {
Use reference parameter to avoid null judgement.

2023-07-19 07:53 UTC, tangjj11 commented on clang/lib/DPCT/ASTTraversal.cpp
> +      isFuncdeclDefTogether(FD) && !FuncInfo->IsAlwaysInlineDevFunc()) {
`decl` --> `Decl`

2023-07-19 07:53 UTC, tangjj11 commented on clang/lib/DPCT/Utility.cpp
> +  if (FD->getMostRecentDecl() != FD) {
Need some comment?

2023-07-19 09:22 UTC, tangjj11 requested changes

2023-07-19 09:22 UTC, tangjj11 commented on clang/test/dpct/test_inline_optimization/test.h
> +#include<cuda_runtime.h>
Need format.

2023-07-20 01:09 UTC, tangjj11 commented on clang/test/dpct/kernel-call.cu
> +
not format

2023-07-20 03:22 UTC, yihanwg approved these changes
LGTM

2023-07-20 08:22 UTC, tangjj11 approved these changes

2023-07-21 00:50 UTC, ShengchenJ commented on clang/lib/DPCT/Utility.cpp
> +bool isFuncDeclDefTogether(const clang::FunctionDecl *FD) {
Could you add more messages about the "together"?

2023-07-21 00:50 UTC, ShengchenJ approved these changes

2023-08-09 03:17 UTC, ziranzha approved these changes

2023-08-09 03:17 UTC, merged