[SYCLomatic] Implement migration for cub::DeviceRunLengthEncode::NonTrivialRuns
oneapi-src/SYCLomatic pull request #1169
Opened 2023-08-15 02:11 UTC by yihanwg

2023-08-15 05:52 UTC, tangjj11 requested changes

2023-08-15 05:52 UTC, tangjj11 commented on clang/test/dpct/cub/devicelevel/nontrivial_run_length_encode.cu
> +}
no new line

2023-08-15 05:55 UTC, yihanwg commented on clang/test/dpct/cub/devicelevel/nontrivial_run_length_encode.cu
> +}
done

2023-08-15 06:32 UTC, tangjj11 approved these changes

2023-08-16 02:16 UTC, ziranzha approved these changes

2023-08-16 02:16 UTC, merged