[SYCLomatic] Implement migration for {CUB_MIN, CUB_MAX, CUB_RUNTIME_FUNCTION}
oneapi-src/SYCLomatic pull request #1176
Opened 2023-08-16 01:30 UTC by yihanwg

2023-08-16 07:19 UTC, tangjj11 requested changes

2023-08-16 07:19 UTC, tangjj11 commented on clang/lib/DPCT/MapNames.cpp
> +                                   "CUB_MAX", "sycl::max")},
should use `getClNamespace`?

2023-08-16 08:35 UTC, yihanwg commented on clang/lib/DPCT/MapNames.cpp
> +                                   "CUB_MAX", "sycl::max")},
done

2023-08-16 08:36 UTC, tangjj11 approved these changes

2023-08-21 07:39 UTC, AndyCHHuang approved these changes
LGTM

2023-08-21 09:17 UTC, zhimingwang36 approved these changes
LGTM

2023-08-21 09:17 UTC, merged