[SYCLomatic] Add some cuSPARSE/cuFFT/cuSolver examples for query-api-mapping
oneapi-src/SYCLomatic pull request #1205
Opened 2023-08-22 09:06 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-08-22 09:40 UTC, wenhuiNi requested changes

2023-08-22 09:40 UTC, wenhuiNi commented on clang/examples/DPCT/lit_cuFFT.cu
> +// RUN: dpct --cuda-include-path="%cuda-path/include" --query-api-mapping=cufftExecZ2Z | FileCheck %s -check-prefix=cufftExecZ2Z
maybe we need remove this file?

2023-08-22 11:43 UTC, zhiweij1 commented on clang/examples/DPCT/lit_cuFFT.cu
> +// RUN: dpct --cuda-include-path="%cuda-path/include" --query-api-mapping=cufftExecZ2Z | FileCheck %s -check-prefix=cufftExecZ2Z
removed

2023-08-23 08:07 UTC, tangjj11 approved these changes
LGTM

2023-08-25 05:57 UTC, zhimingwang36 commented on clang/test/dpct/query_api_mapping/cuSPARSE/lit_cuSPARSE.cu
> +// cusparseSpMM_preprocess-EMPTY:
migration result is empty?

2023-08-25 06:21 UTC, zhiweij1 commented on clang/test/dpct/query_api_mapping/cuSPARSE/lit_cuSPARSE.cu
> +// cusparseSpMM_preprocess-EMPTY:
fixed

2023-08-28 01:38 UTC, zhimingwang36 approved these changes
LGTM

2023-08-28 01:40 UTC, merged