[SYCLomatic] Add mapping query for 20 CUB APIs
oneapi-src/SYCLomatic pull request #1234
Opened 2023-08-28 09:49 UTC by yihanwg

2023-08-28 09:52 UTC, tangjj11 requested changes

2023-08-28 09:52 UTC, tangjj11 commented on clang/examples/DPCT/CUB/cub$$DeviceScan$$InclusiveScanByKey.cu
> +}
no new line

2023-08-28 09:52 UTC, tangjj11 commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_ARG_MAX-NEXT:  dpct::reduce_argmax(oneapi::dpl::execution::device_policy(*stream), d_in, d_out, num_items);
need add like other lit test:
// CHECK_REDUCE_ARG_MAX-EMPTY:

2023-08-28 09:58 UTC, yihanwg commented on clang/examples/DPCT/CUB/cub$$DeviceScan$$InclusiveScanByKey.cu
> +}
fixed

2023-08-28 09:58 UTC, wenhuiNi approved these changes

2023-08-28 10:02 UTC, tangjj11 approved these changes

2023-08-28 11:42 UTC, yihanwg commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_ARG_MAX-NEXT:  dpct::reduce_argmax(oneapi::dpl::execution::device_policy(*stream), d_in, d_out, num_items);
fixed

2023-08-30 01:00 UTC, zhimingwang36 commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_MAX-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
Please declare a stream variable.

2023-08-30 01:00 UTC, zhimingwang36 commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_MIN-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
same as above.

2023-08-30 01:00 UTC, zhimingwang36 commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_SUM-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
same as above.

2023-08-30 01:00 UTC, zhimingwang36 commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_BY_KEY-NEXT:   stream->fill(d_num_runs_out, std::distance(d_unique_out, oneapi::dpl::reduce_by_key(oneapi::dpl::execution::device_policy(*stream), d_keys_in, d_keys_in + num_items, d_
same as above.

2023-08-30 03:54 UTC, yihanwg commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_MAX-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
fixed

2023-08-30 03:54 UTC, yihanwg commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_MIN-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
fixed

2023-08-30 03:54 UTC, yihanwg commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_BY_KEY-NEXT:   stream->fill(d_num_runs_out, std::distance(d_unique_out, oneapi::dpl::reduce_by_key(oneapi::dpl::execution::device_policy(*stream), d_keys_in, d_keys_in + num_items, d_
fixed

2023-08-30 03:54 UTC, yihanwg commented on clang/test/dpct/query_api_mapping/CUB/cub_device.cu
> +// CHECK_REDUCE_SUM-NEXT:   stream->fill(d_out, oneapi::dpl::reduce(oneapi::dpl::execution::device_policy(*stream), d_in, d_in + num_items, typename std::iterator_traits<decltype(d_out)>::value_type{
fixed

2023-08-31 00:39 UTC, zhimingwang36 approved these changes
LGTM

2023-08-31 00:39 UTC, merged