[SYCLomatic] Refine the logic to remove wait
oneapi-src/SYCLomatic pull request #1284
Opened 2023-09-08 09:09 UTC by intwanghao

2023-09-18 03:01 UTC, ziranzha commented on clang/lib/DPCT/Utility.cpp
> +        if (dpct::DpctGlobalInfo::getTypeName(D->getType()) == "cudaError_t") {
Check the type at first.

2023-09-19 03:34 UTC, ziranzha commented on clang/lib/DPCT/Utility.cpp
> +  auto CheckIfDstImpactNextCE = [&](const CallExpr *CurCE,
Can we check it in above logic?

2023-09-26 03:30 UTC, ziranzha approved these changes

2023-10-09 08:32 UTC, zhimingwang36 requested changes

2023-10-09 08:32 UTC, zhimingwang36 commented on clang/lib/DPCT/Utility.cpp
> +        if (!D) {
this function is quite big now,  ~300 line.  Difficult to understand the framework of this function, please refactor the code.

2023-10-09 08:32 UTC, zhimingwang36 commented on clang/test/dpct/USM-restricted.cu
> +  // CHECK: MY_SAFE_CALL(DPCT_CHECK_ERROR(q_ct1.memcpy((char *)(constData.get_ptr()) + 1, h_A, size)));
what is the migration result if h_A is updated b/w two API.

2023-10-09 08:32 UTC, zhimingwang36 commented on clang/lib/DPCT/Utility.cpp
> +/// Find all related DREs with the declarations in \p VDSet. Except the DREs in
Please update the comment by more detail or relationship b/w args.

2023-10-12 08:46 UTC, zhimingwang36 approved these changes
LGTM

2023-10-12 08:48 UTC, merged