[SYCLomatic] Bugfix for initialization of device_vector from different type pointer
oneapi-src/SYCLomatic pull request #1300
Opened 2023-09-13 17:45 UTC by danhoeflinger

This resolves a bug when initializing a `dpct::device_vector<T>` from a pointer of a different type than `T`.

2023-09-13 18:30 UTC, timmiesmith approved these changes
LGTM. Thank you.

2023-09-14 00:32 UTC, tomflinda approved these changes
LGTM

2023-09-14 02:01 UTC, tomflinda requested changes
After a further thought, the fixing PR still has problems, I have commented it in the JIRA ticket.

2023-09-15 03:15 UTC, tomflinda approved these changes
LGTM

2023-09-15 08:49 UTC, merged