[SYCLomatic]Refine the migration of __funnelshift_*
oneapi-src/SYCLomatic pull request #1301
Opened 2023-09-14 02:51 UTC by wenhuiNi

Refine the migartion of `__funnelshift_l`,  `__funnelshift_lc`, `__funnelshift_r`, `__funnelshift_rc`
Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

2023-09-14 06:55 UTC, tangjj11 requested changes

2023-09-14 06:55 UTC, tangjj11 commented on clang/lib/DPCT/CallExprRewriterMath.cpp
> +      OS << "((" << Namespace << "upsample("
Need consider the args type is the same as param?

2023-09-15 01:24 UTC, tangjj11 approved these changes

2023-09-15 01:24 UTC, tangjj11 commented on clang/lib/DPCT/CallExprRewriterMath.cpp
> +         << (Call->getArg(0)->IgnoreImplicit()->getType().getAsString(
Can extract a common variable like line: 683.

2023-09-26 03:40 UTC, ziranzha approved these changes

2023-09-26 03:40 UTC, merged