[SYCLomatic] Cleanup dpct::tagged_pointer and dpct::release_temporary_allocation
oneapi-src/SYCLomatic pull request #1396
Opened 2023-11-02 21:09 UTC by mmichel11

This PR cleans up the function signatures of dpct::tagged_pointer and dpct::release_temporary_allocation to enable easier migration to these APIs by the SYCLomatic team.

Please note that these changes will cause SYCLomatic tests to fail until the corresponding test PR changes are merged.

2023-11-06 16:12 UTC, danhoeflinger approved these changes
LGTM

2023-11-06 16:32 UTC, danhoeflinger commented
> LGTM

Thinking a little more, I don't like the extra (ignored) parameter for `release_temporary_allocation`.  It seems to me that this shouldn't be there if we aren't doing something with it.  

Should this third param just be discarded by SYCLomatic in migration instead if we are just ignoring it?

2023-11-06 16:34 UTC, danhoeflinger requested changes
> LGTM

Thinking a little more, I don't like the extra (ignored) parameter for `release_temporary_allocation`.  It seems to me that this shouldn't be there if we aren't doing something with it.  

Should this third param just be discarded by SYCLomatic in migration instead if we are just ignoring it?

2023-11-06 16:38 UTC, mmichel11 commented
> > LGTM
> 
> Thinking a little more, I don't like the extra (ignored) parameter for `release_temporary_allocation`. It seems to me that this shouldn't be there if we aren't doing something with it.
> 
> Should this third param just be discarded by SYCLomatic in migration instead if we are just ignoring it?

@tomflinda Do you have any objection to this? It would mean the `n` parameter (number of elements to release) would just be ignored in mapping as it is unnecessary with `sycl::free`.

2023-11-06 16:47 UTC, danhoeflinger commented
> @tomflinda Do you have any objection to this? It would mean the `n` parameter (number of elements to release) would just be ignored in mapping as it is unnecessary with `sycl::free`.

To provide a bit more justification for my stance.
If we add and ignore this third parameter:
1) It adds an extra (false) requirement to the user to keep track of the size of allocations
2) It makes it seem like the user has extra functionality which is not there.  We do not have the ability to free only part of what was allocated, we also do not check to make sure that the number provided is the same as what was originally allocated and throw or provide any error.

2023-11-08 07:45 UTC, tomflinda commented
> we are



> > > LGTM
> > 
> > 
> > Thinking a little more, I don't like the extra (ignored) parameter for `release_temporary_allocation`. It seems to me that this shouldn't be there if we aren't doing something with it.
> > Should this third param just be discarded by SYCLomatic in migration instead if we are just ignoring it?
> 
> @tomflinda Do you have any objection to this? It would mean the `n` parameter (number of elements to release) would just be ignored in mapping as it is unnecessary with `sycl::free`.
No, I haven't, you can discard the third param, I'm OK the change.

2023-11-08 07:48 UTC, tomflinda commented
> > @tomflinda Do you have any objection to this? It would mean the `n` parameter (number of elements to release) would just be ignored in mapping as it is unnecessary with `sycl::free`.
> 
> To provide a bit more justification for my stance. If we add and ignore this third parameter:
> 
> 1. It adds an extra (false) requirement to the user to keep track of the size of allocations
> 2. It makes it seem like the user has extra functionality which is not there.  We do not have the ability to free only part of what was allocated, we also do not check to make sure that the number provided is the same as what was originally allocated and throw or provide any error.

OK to me to ignore the third parameter.

2023-11-08 17:55 UTC, mmichel11 commented
@danhoeflinger @tomflinda I have removed the third parameter in `dpct::release_temporary_allocation`. The only change now is reordering the templated parameters for `dpct::tagged_pointer`.

2023-11-08 18:11 UTC, danhoeflinger approved these changes
LGTM

2023-11-11 01:31 UTC, tomflinda approved these changes
LGTM

2023-11-20 18:26 UTC, danhoeflinger commented
@zhimingwang36 @tomflinda I think this is ready to merge.

2023-12-05 03:02 UTC, ziranzha approved these changes

2023-12-06 01:04 UTC, merged