[SYCLomatic] Optimize the implementation of dpct::bit_reverse
oneapi-src/SYCLomatic pull request #1424
Opened 2023-11-14 07:48 UTC by yihanwg

Signed-off-by: Wang, Yihan <yihan.wang@intel.com>

2023-11-14 07:56 UTC, wenhuiNi approved these changes

2023-11-14 07:57 UTC, tangjj11 requested changes

2023-11-14 07:57 UTC, tangjj11 commented on clang/runtime/dpct-rt/include/util.hpp
> +/// Copied from llvm/Support/MathExtras.h
please move to math.hpp

2023-11-14 08:00 UTC, tangjj11 commented on clang/runtime/dpct-rt/include/util.hpp
> +static const unsigned char BitReverseTable256[256] = {
can move to detail?

2023-11-14 08:05 UTC, tangjj11 approved these changes

2023-11-14 08:12 UTC, yihanwg commented on clang/runtime/dpct-rt/include/util.hpp
> +/// Copied from llvm/Support/MathExtras.h
Will it cause compatibility issues?

2023-11-14 08:15 UTC, yihwang-nv commented on clang/runtime/dpct-rt/include/util.hpp
> +static const unsigned char BitReverseTable256[256] = {
Ok, done.

2023-12-25 06:47 UTC, zhimingwang36 approved these changes
LGTM

2024-10-22 01:58 UTC, zhimingwang36 commented
Close it,  As CPU side test fail.

2024-10-22 01:58 UTC, closed without merging