[SYCLomatic]Fix auto pulldown conflict from sycl to SYCLomatic
oneapi-src/SYCLomatic pull request #1428
Opened 2023-11-15 07:01 UTC by wenhuiNi

2023-11-15 07:22 UTC, tangjj11 requested changes

2023-11-15 07:22 UTC, tangjj11 commented on .github/workflows/docs.yml
> +          TZ=UTC ninja -C lld-build docs-lld-html
no new line

2023-11-16 01:48 UTC, tomflinda approved these changes
LGTM

2023-11-16 03:21 UTC, tangjj11 approved these changes

2023-11-16 03:25 UTC, ziranzha approved these changes

2023-11-17 05:44 UTC, merged