[SYCLomatic] Add API query for cuDNN APIs
oneapi-src/SYCLomatic pull request #1448
Opened 2023-11-24 07:25 UTC by intwanghao

2023-11-24 07:51 UTC, tangjj11 requested changes

2023-11-24 07:51 UTC, tangjj11 commented on clang/test/dpct/query_api_mapping/cuDNN/dnn_part1.cu
> +///dpct --cuda-include-path="/rdrive/ref/cuda/lin/cuda-12.2/include" --query-api-mapping=cudnnBatchNormalizationBackward
needn't this line

2023-11-24 07:51 UTC, tangjj11 commented on clang/test/dpct/query_api_mapping/cuDNN/dnn_part1.cu
> +// cudnnTransformTensor-NEXT:   h.async_reorder(*alpha, src_d, src, *beta, dst_d, dst);
Please observe the lit CI test time. If it is too long, need split this lit file to several files (may refer the CUDA doc's chapter).

2023-11-29 01:19 UTC, tangjj11 approved these changes

2023-11-29 03:53 UTC, zhimingwang36 approved these changes
LGTM

2023-11-29 03:54 UTC, merged