[SYCLomatic] Improve DPCT026 message
oneapi-src/SYCLomatic pull request #1465
Opened 2023-11-30 06:24 UTC by yihanwg

2023-11-30 09:16 UTC, tangjj11 requested changes

2023-11-30 09:16 UTC, tangjj11 commented on clang/lib/DPCT/CallExprRewriter.h
> +        Message.empty() ? "this functionality is redundant in SYCL." : Message;
The title `Improve DPCT026 message` should be `Improve DPCT1026 message`

2023-11-30 09:17 UTC, yihwang-nv commented on clang/lib/DPCT/CallExprRewriter.h
> +        Message.empty() ? "this functionality is redundant in SYCL." : Message;
done

2023-11-30 09:19 UTC, tangjj11 approved these changes

2023-12-12 01:49 UTC, zhimingwang36 approved these changes
LGTM

2023-12-12 01:50 UTC, merged