[SYCLomatic] Execute device synchronization before device pointer free
oneapi-src/SYCLomatic pull request #1511
Opened 2023-12-11 08:06 UTC by intwanghao

2024-01-04 02:12 UTC, tangjj11 requested changes

2024-01-04 02:12 UTC, tangjj11 commented on clang/lib/DPCT/ASTTraversal.cpp
> +        NewFuncName = MapNames::getClNamespace() + "free";
may need a `{{NEEDREPLACEQ}}.wait_and_throw()` before the `sycl::free`?

2024-01-04 02:12 UTC, tangjj11 commented on clang/lib/DPCT/ASTTraversal.cpp
> +        NewFuncName = MapNames::getDpctNamespace() + "dpct_free";
can use `Repl <<` directly, needn't the `NewFuncName` variable.

2024-01-04 02:12 UTC, tangjj11 commented on clang/test/dpct/vector_add_format.cu
> -  cudaFree(d_A);
can change the `CHECK` but not delete.

2024-01-04 05:30 UTC, tangjj11 approved these changes

2024-01-05 06:45 UTC, zhimingwang36 commented on clang/runtime/dpct-rt/include/dpct/memory.hpp
> +  dpct::get_current_device().queues_wait_and_throw();
L835 is not required in USM_none

2024-01-05 06:50 UTC, zhimingwang36 commented on clang/test/dpct/cub/devicelevel/device_reduce_arg_max.cu
> +// CHECK-NOT: dpct::dpct_free({{.*}})
Please config migrate to sycl::free  if "---optimize-migration" is specified.

2024-01-09 02:41 UTC, zhimingwang36 approved these changes
LGTM

2024-01-09 02:43 UTC, merged