[SYCLomatic]Enbale the migration of cuDeviceGetUuid
oneapi-src/SYCLomatic pull request #1514
Opened 2023-12-12 05:25 UTC by wenhuiNi

2023-12-12 08:02 UTC, tangjj11 requested changes

2023-12-12 08:02 UTC, tangjj11 commented on clang/runtime/dpct-rt/include/dpct/device.hpp
> +  return 999;
this line can be moved out of macro `if`?

2023-12-12 08:03 UTC, yihanwg commented on clang/runtime/dpct-rt/include/dpct/device.hpp
> +  return 999;
Let's use `dpct::error_code::default_error` instead a magic number here.

2023-12-14 06:30 UTC, AndyCHHuang approved these changes
LGTM

2023-12-15 01:33 UTC, tangjj11 approved these changes

2023-12-20 09:02 UTC, ziranzha approved these changes

2023-12-20 09:02 UTC, merged