Lit test for find_package CMake macro
oneapi-src/SYCLomatic pull request #1549
Opened 2023-12-21 04:34 UTC by TejaX-Alaghari

Adding lit test for find_package CMake macro

2023-12-25 02:31 UTC, tomflinda commented on clang/test/dpct/cmake_migation/case_008/expected.txt
> +#find_package(OpenMP REQUIRED)
Pls add comments to explain why these two lines are  disabled.

2023-12-25 02:32 UTC, tomflinda commented on clang/test/dpct/cmake_migation/case_008/expected.txt
> +find_package(oneDPL REQUIRED)
Have you verified these two mapping are the correct mappings for :
find_package(CUDNN REQUIRED cudnn)
find_package(CUB REQUIRED)

2023-12-25 02:34 UTC, tomflinda commented on clang/tools/dpct/cmake/dpct.cmake
> +macro(DPCT_FIND_PACKAGE package)
Pls add behavior test for this help function in https://github.com/oneapi-src/SYCLomatic-test

2024-01-02 08:55 UTC, zhiweij1 commented on clang/tools/dpct/cmake/dpct.cmake
> +      package_name STREQUAL "sparse" OR
```suggestion
      package_name STREQUAL "cusparse" OR
```

2024-01-02 08:56 UTC, zhiweij1 commented on clang/tools/dpct/cmake/dpct.cmake
> +      package_name STREQUAL "solver" OR
```suggestion
      package_name STREQUAL "cusolver" OR
```

2024-01-02 08:56 UTC, zhiweij1 commented on clang/tools/dpct/cmake/dpct.cmake
> +      package_name STREQUAL "sparse_static" OR
```suggestion
      package_name STREQUAL "cusparse_static" OR
```

2024-01-02 08:56 UTC, zhiweij1 commented on clang/tools/dpct/cmake/dpct.cmake
> +      package_name STREQUAL "solver_static" OR
```suggestion
      package_name STREQUAL "cusolver_static" OR
```

2024-01-02 08:57 UTC, tomflinda commented on clang/tools/dpct/cmake/dpct.cmake
> +      package_name STREQUAL "sparse" OR
Pls make sure the cuda libraries are valid arguments for find_package in cuda side?

2024-01-02 08:58 UTC, zhiweij1 requested changes
I'm not sure the library parameter of the `find_package` API.
Should it have `CUDA::` prefix like `CUDA::cusolver`?

2024-01-02 10:09 UTC, TejaX-Alaghari commented
> I'm not sure the library parameter of the `find_package` API. Should it have `CUDA::` prefix like `CUDA::cusolver`?

Below are a few configs I've tired - 

find_package(cublas REQUIRED)                                 --> Could not find a package configuration file provided by "cublas"
find_package(CUDAToolkit REQUIRED cublas)            --> No error
find_package(CUDAToolkit REQUIRED CUDA::cublas) --> No error

2024-01-03 05:24 UTC, tomflinda commented on clang/test/dpct/cmake_migration/case_008/expected.txt
> +dpct_find_package(CUDAToolkit REQUIRED cublas cufft nvToolsExt)
After a further thought, cuda libraries "cublas cufft nvToolsExt" should not be appeared in sycl macro/functions, which will confuse users,  we should migrate these libraries' name in yaml based rules.

2024-01-10 00:29 UTC, tomflinda requested changes

2024-01-10 00:29 UTC, tomflinda commented on clang/test/dpct/cmake_migration/case_001/expected.txt
> +dpct_helper_find_package(IntelSYCL REQUIRED)
After a further thought, find_package() is not a cuda specific cmake syntax, so to introduce dpct_helper_find_package is a little over designed.
we can map cuda specific argument used in find_package() to sycl mappings if the mapping is available, or "" if mapping is not available.

As to mapping argument related to MKL, we can introduce a help variable like [DNN_LIB ](https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/tools/dpct/cmake/dpct.cmake#L95C9-L95C15) to simple migration implementation.

2024-01-10 02:17 UTC, zhimingwang36 commented on clang/test/dpct/cmake_migration/case_008/input.cmake
> +find_package(CUDAToolkit REQUIRED curand cufft cusparse_static cublas cusolver)
I'd prefer to migrate to: 
find_package(IntelSYCL)
find_package(MKL)
find_pakcage(DPL)

Don't introduce helper function for stadard find_package().  There is overhead to main the helper function.

2024-01-10 08:52 UTC, tomflinda commented on clang/tools/dpct/DpctOptRules/cmake_script_migration_rule.yaml
> +- Rule: rule_set
This base is not needed.

2024-01-10 08:53 UTC, tomflinda commented on clang/tools/dpct/DpctOptRules/cmake_script_migration_rule.yaml
> +      Out: ${arg}.dp.cpp
This rule is not need, pls remove it.

2024-01-10 08:56 UTC, tomflinda requested changes
Pls rebase your PR to latest code

2024-01-10 08:58 UTC, zhimingwang36 commented on clang/tools/dpct/DpctOptRules/cmake_script_migration_rule.yaml
> +  CmakeSyntax: cub_find_package
I'd prefer find_package as the base name for the rule.  eg.  find_package-cub, finally this name will be used for end user if some rule is conflicted against each other.

2024-01-11 03:24 UTC, tomflinda requested changes
Pls rebase your PR to latest code repo to make sure CI test pass

2024-01-11 03:25 UTC, zhimingwang36 approved these changes
LGTM

2024-01-12 08:24 UTC, zhiweij1 approved these changes

2024-01-12 09:19 UTC, tomflinda approved these changes
LGMT

2024-01-16 08:39 UTC, merged