[SYCLomatic] Implement help function for reduction,binary,convolution,batchnormalization
oneapi-src/SYCLomatic pull request #159
Opened 2022-08-17 07:25 UTC by intwanghao

Signed-off-by: Hao Wang <hao3.wang@intel.com>

2022-08-25 02:12 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  static size_t get_element_num(memory_desc_ext desc) {
how about move it to member function?

2022-08-25 02:15 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  if (ndims == 5) {
how to process ndims > 5?

2022-08-25 02:17 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +    std::vector<std::tuple<float, float, memory_desc_ext, void *>> args) {
how about use a struct for the tuple?

2022-08-25 02:33 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  template <typename T> struct no_zero_op {
how about move the struct into function transform_no_zero?

2022-08-25 02:33 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +      throw std::runtime_error("fill: unsupported data type sycl::bfloat16.");
bfloat16 is supported in latest compiler

2022-08-25 02:35 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +    int arg_index = std::get<2>(extra_arg);
The name arg_index is confused

2022-08-25 02:43 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  if (use_attr) {
if constexpr (use_attr)

2022-08-25 02:50 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  std::map<void *, void *> caches_map;
how about use std;:vector<void *> to store the allocated memory?

2022-08-25 02:51 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  if (use_attr) {
same as above

2022-08-25 03:03 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +        src_desc_0.get_desc(), -1.f, 1.f);
add some comments

2022-08-25 03:19 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  ::dnnl::algorithm onednn_algorithm;
how about use code like:
cache = nullptr;
switch () {
  case ...:
     cache = allocate();
     do something;
     src = cache;
     break;
   }
   event = execute();
   if (cache)
     async_dpct_free(...)

2022-08-25 03:23 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +bool engine_ext::scale_parameter_preprocess(
add some comments

2022-08-29 07:52 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +#include <oneapi/dpl/algorithm>
Should insert before <CL/sycl.hpp>, double check with Andy.

2022-08-29 08:35 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +    caches.push_back(reordered_saved_mean);
move it into if stmt at line:2091

2022-08-29 08:50 UTC, ziranzha commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
>          {DNNL_ARG_SRC, ::dnnl::memory(src_desc.get_desc(), _eng, cache)}};
execution stmt can be moved outside if.

2022-08-30 08:29 UTC, LongZhenhai commented
comment test

2022-08-31 00:11 UTC, YuriPlyakhin requested changes, later dismissed
Please, split formatting changes and new help function implementation into 2 separate pull requests.

2022-08-31 13:56 UTC, intwanghao commented
> Please, split formatting changes and new help function implementation into 2 separate pull requests.

Done

2022-10-14 01:33 UTC, closed without merging