[SYCLomatic] Fix get_info in device.hpp
oneapi-src/SYCLomatic pull request #161
Opened 2022-08-18 22:05 UTC by LU-JOHN

Fix get_info call in device.hpp to match SYCL 2020 standard.

Signed-off-by: Lu, John <john.lu@intel.com>

2022-09-12 18:28 UTC, YuriPlyakhin requested changes
Changes are needed:
1.	Please, introduce DPC++ compiler-specific check to make sure the code works fine with older and newer DPC++ compilers. Just clearly comment it out that this code is specific to a certain compiler
2.	Please, do not add compatibility with SYCL 1.2.1

Hence, the code should be something like:

#if (DPC++ compiler specific check for older compiler)
        // comment saying that it is a branch specific for syclos compiler older than …, where max_work_item_sizes is an enum class element
        get_info<cl::sycl::info::device::max_work_item_sizes>());
#else
        // SYCL 2020-conformant code, max_work_item_sizes is a struct templated by an int
        get_info<cl::sycl::info::device::max_work_item_sizes<3>>());
#endif

2022-09-13 17:12 UTC, YuriPlyakhin requested changes

2022-09-13 17:12 UTC, YuriPlyakhin commented on clang/runtime/dpct-rt/include/device.hpp.inc
> +        // syclos compiler older than 2022/09/02, where max_work_item_sizes is an enum class element
```suggestion
        // oneAPI DPC++ compiler older than 2022/09/02, where max_work_item_sizes is an enum class element
```

2022-09-13 21:53 UTC, YuriPlyakhin approved these changes

2022-09-13 23:01 UTC, 0x12CC approved these changes

2022-09-14 01:28 UTC, zhimingwang36 approved these changes
LGTM

2022-09-14 01:30 UTC, merged