[SYCLomatic] Add tag for different rewriters for math API
oneapi-src/SYCLomatic pull request #1616
Opened 2024-01-12 07:18 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2024-01-12 07:19 UTC, zhiweij1 commented on clang/lib/DPCT/CallExprRewriterMath.cpp
> +  _8,
remove

2024-03-05 03:00 UTC, zhiweij1 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +createMathRewriterFactory(
use args...

2024-03-05 03:00 UTC, zhiweij1 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  std::unordered_map<
use array

2024-03-05 03:00 UTC, zhiweij1 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +      Tag, std::tuple<std::function<bool(const CallExpr *)>,
use std::pair

2024-03-15 05:42 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  device_perf = 0,
Please add comment for the meaning of each ENUM value.

2024-03-15 05:45 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  std::shared_ptr<CallExprRewriter> getDeviceRewriter(const CallExpr *C) const {
Please add a comment for the priority.

2024-03-15 05:47 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  std::shared_ptr<CallExprRewriter> create(const CallExpr *C) const override {
Please add comment for the priority decision.

2024-03-15 05:51 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +enum class Tag : size_t {
if only used by math, may move to math:: namespace or rename to math..tag.

2024-03-19 01:58 UTC, tangjj11 requested changes

2024-03-19 01:58 UTC, tangjj11 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  Rewriters[static_cast<size_t>(Tag)] = std::make_pair(Cond, Rewriter);
Please add a duplicated check and report error.

2024-03-19 02:52 UTC, tangjj11 approved these changes

2024-03-25 05:46 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  host_perf,        // host API for performace
```suggestion
  host_perf,        // host API for performance
```

2024-03-25 05:46 UTC, zhimingwang36 commented on clang/lib/DPCT/Rewriters/Math/CallExprRewriterMath.h
> +  device_perf = 0,  // device API for performace
```suggestion
  device_perf = 0,  // device API for performance
```

2024-03-25 05:50 UTC, zhimingwang36 approved these changes
LGTM

2024-03-25 05:51 UTC, merged