[SYCLomatic] Fix exclusive_scan migration bug
oneapi-src/SYCLomatic pull request #164
Opened 2022-08-22 20:08 UTC by 0x12CC

This change fixes migration of `thrust::exclusive_scan` calls where the initial value is not specified.

Signed-off-by: Michael Aziz <michael.aziz@intel.com>

2022-08-26 00:24 UTC, tomflinda commented on clang/lib/DPCT/APINamesThrust.inc
> +)
thrust::exclusive_scan() has six function template declarations, more detail pls refer to https://thrust.github.io/doc/group__prefixsums_ga0f1b7e1931f6ccd83c67c8cfde7c8144.html#ga0f1b7e1931f6ccd83c67c8cfde7c8144, your rewrite mapping code here should cover all these six function template declarations.

For example, thrust::copy_if() has four function template declarations, and Line1372~Line1413 covers all these four declarations.

2022-08-26 00:46 UTC, tomflinda commented on clang/lib/DPCT/APINamesThrust.inc
> +  HeaderType::HT_Numeric,
Line1421 is not needed

2022-08-29 00:44 UTC, zhiweij1 approved these changes

2022-08-29 00:49 UTC, zhiweij1 commented on clang/lib/DPCT/APINamesThrust.inc
> +  // thrust::exclusive_scan(data, data + 6, data)
Need add additional condition to check the iterator is host/device (like line 1384)

2022-08-29 00:49 UTC, zhiweij1 commented on clang/lib/DPCT/APINamesThrust.inc
> +      CALL_FACTORY_ENTRY("thrust::exclusive_scan",
Need add additional condition to check the iterator is host/device (like line 1384)

2022-08-29 00:50 UTC, zhiweij1 requested changes
Please check the iterator type for case:
thrust::exclusive_scan(data, data + 6, data) and
thrust::exclusive_scan(data, data + 6, data, 4);

2022-08-29 03:31 UTC, tomflinda commented on clang/test/dpct/thrust-algo.cu
> +  thrust::exclusive_scan(v.begin(), v.end(), v2.begin());
As v.begin(), v.end(), v2.begin() are host iterator, we should use "oneapi::dpl::execution::seq" in the migrated code. 
if v.begin(), v.end(), v2.begin() are device iterator, we should use "oneapi::dpl::execution::make_device_policy(q_ct1)" in the migrated code.
You can refer to Line244, Line245.

2022-08-29 21:03 UTC, 0x12CC commented
I've changed the migration to check the iterator type for the three overloads where the execution policy is unspecified.

2022-08-31 00:03 UTC, tomflinda approved these changes
LGTM

2022-08-31 00:06 UTC, zhiweij1 approved these changes

2022-08-31 07:10 UTC, zhimingwang36 approved these changes
LGTM

2022-08-31 07:10 UTC, merged