[SYCLomatic][codepin] Copy untouched original file(s) into debug folder
oneapi-src/SYCLomatic pull request #1676
Opened 2024-01-29 06:37 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2024-01-30 02:48 UTC, wenhuiNi approved these changes

2024-01-30 08:26 UTC, zhimingwang36 commented on clang/lib/DPCT/SaveNewFiles.cpp
> +      if (!rewriteDir(DebugFilePath, InRoot, DebugCUDAFolder)) {
add isCodePinEnabled()?

2024-01-30 08:27 UTC, zhimingwang36 commented on clang/lib/DPCT/SaveNewFiles.cpp
> +    clang::tooling::UnifiedPath DebugFilePath = Entry.first;
comment the diff between the 3 FilePath

2024-01-30 08:29 UTC, zhimingwang36 requested changes
Please update the commit msg.

2024-01-31 01:56 UTC, zhimingwang36 approved these changes
LGTM

2024-01-31 01:56 UTC, merged