[SYCLomatic] CodePin doc
oneapi-src/SYCLomatic pull request #1711
Opened 2024-02-08 07:20 UTC by AndyCHHuang

2024-02-14 01:16 UTC, lapel22 requested changes
Suggested some grammar, spelling, and punctuation fixes. Once changes are made and approved, files can be merged

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +There are cases that the migrated SYCL program has different runtime behavior to
Change to "There are some cases where the migrated SYCL program may have runtime behavior that differs from the original CUDA program. Reasons for this inconsistency include: "

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +CodePin is introduced as a sub-feature of |tool_name| to reduce the effort of
change to "in order to reduce the effort of debugging such inconsistencies in runtime behavior."

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +will not only migrate the CUDA program to SYCL but also generate instrumented
Suggest changing to "migrate the CUDA program to SYCL, but will also generate an instrumented version of the CUDA program."

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +The instrumented code will dump the data of related variables before/after
suggest changing to "The instrumented code will dump the data of related variables, before/after selected API or kernel calls, into a report."

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +from the CUDA and SYCL program helps identify the point of divergent behavior.
Change to "can help identify the source of divergent runtime behavior."

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +The example CUDA code has an issue in the cudaMemcpy() before the vectorAdd kernel call,
Change to "vectorAdd kernel call: "

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +which causes incorrect behavior of the migrated SYCL program because ``int3`` will be
Change to ", which causes incorrect behavior of the migrated SYCL program. This is because"

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +migrated to ``sycl::int3`` and the size of ``sycl::int3`` is 16 bytes not 12 bytes.
Add a comma after 16 bytes

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +To debug the issue, user can migrate the CUDA program with CodePin enabled.
"issue, the user can"

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +After the migration, there will be 2 files ``dpct_output/example.dp.cpp`` and ``dpct_output_debug/example.cu``.
Change to "2 files: "

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +After building and executing ``dpct_output/example.dp.cpp`` and ``dpct_output_debug/example.cu``, following report will be generated.
Change to "the following report will be generated"

2024-02-14 01:16 UTC, lapel22 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +The report helps the user to identify where the runtime behaivor of the CUDA and the SYCL version start diverge.
Change to "where the runtime behavior of the CUDA and the SYCL version start to diverge from one another."

2024-02-26 17:52 UTC, lapel22 approved these changes
Looks good to me!

2024-02-27 01:43 UTC, zhimingwang36 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +* Difference in arithmetic precision between hardware.
```suggestion
* Difference in arithmetic precision between hardware
```

2024-02-27 01:45 UTC, zhimingwang36 commented on docs/dev_guide/migration/debug-with-codepin.rst
> +When CodePin is enabled, |tool_name| will migrate the CUDA program to SYCL, but will also generate an instrumented version of the CUDA program.
```suggestion
When CodePin is enabled, |tool_name| will migrate the CUDA program to SYCL, and will also generate an instrumented version of the CUDA program.
```

2024-02-27 02:00 UTC, zhimingwang36 approved these changes
LGTM

2024-02-27 02:01 UTC, merged