[SYCLomatic][Doc] Add doc description for analysis mode
oneapi-src/SYCLomatic pull request #1712
Opened 2024-02-08 08:35 UTC by ziranzha

2024-02-08 09:35 UTC, zhimingwang36 approved these changes
LGTM

2024-02-29 03:49 UTC, lapel22 requested changes
Reviewed and left comments!

2024-02-29 03:49 UTC, lapel22 commented on docs/dev_guide/migration/analysis-mode.rst
> +Analysis Mode generates a summary report that shows how many lines of code are migrated with confidence and how many lines of code are not migrated perfectly due to the language gap between CUDA and
Suggest change to "Analysis Mode generates a summary report showing how many lines of code are migrated with confidence, and how many lines of code are migrated imperfectly due to the language gap between CUDA and SYCL. The report also provides an estimation of how much human effort will be required to complete the code migration. Three "effort levels" have been defined: low effort, medium effort, and high effort. All migration issues are classified into these levels. Typically, a low effort level indicates issues that the developer can solve in minutes, whereas a medium effort level indicates an issue that may take hours to solve. If a high effort level issue is reports, this unfortunately means that there is not yet an equivalent functionality provided in SYCL or SYCL ecosystem libraries for the CUDA API or the CUDA library API.  In these cases, the developer will need to manually rewrite the functionality."

2024-02-29 03:49 UTC, lapel22 commented on docs/dev_guide/migration/analysis-mode.rst
> +Following is an example of analysis report:
Change to "An example analysis report can be seen as follows:"

2024-03-05 06:31 UTC, zhimingwang36 commented on docs/dev_guide/migration/analysis-mode.rst
> +Following is an example of analysis report:
fixed.

2024-03-05 06:32 UTC, merged