[SYCLomatic] make the option "--enable-profiling" is enabled on demand
oneapi-src/SYCLomatic pull request #1729
Opened 2024-02-22 09:03 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2024-02-23 06:09 UTC, zhimingwang36 commented on clang/include/clang/DPCT/DPCTOptions.inc
> +           llvm::cl::desc("Enable SYCL queue profiling in helper functions on demand. \n"),
default: auto  (auto: mean off: if tool conclude profiling is not required, on: if tool conclude profiling is required).

2024-02-27 00:57 UTC, zhiweij1 commented on clang/lib/DPCT/ASTTraversal.cpp
> +void ProfilingEnableOnDemandRule::registerMatcher(MatchFinder &MF) {
Can it be merged into EventAPICallRule?

2024-02-27 01:09 UTC, zhiweij1 commented on clang/lib/DPCT/AnalysisInfo.cpp
>      concatHeader(OS, getHeaderSpelling(Type));
Line 907 also has getEnablepProfilingFlag

2024-02-27 01:10 UTC, zhiweij1 commented on clang/lib/DPCT/AnalysisInfo.cpp
> +
```suggestion
```

2024-02-27 01:11 UTC, zhiweij1 commented on clang/lib/DPCT/ASTTraversal.cpp
> +
```suggestion
```

2024-02-27 01:12 UTC, zhiweij1 requested changes
Please update the PR

2024-02-27 01:33 UTC, tomflinda commented on clang/lib/DPCT/ASTTraversal.cpp
> +
okay

2024-02-27 01:33 UTC, tomflinda commented on clang/lib/DPCT/AnalysisInfo.cpp
> +
okay

2024-02-28 01:33 UTC, zhiweij1 approved these changes

2024-02-28 05:45 UTC, zhimingwang36 commented on clang/include/clang/DPCT/DPCTOptions.inc
> +                   "auto\n(auto: mean off: if tool concludes profiling is not "
```suggestion
                   "auto (enable-profiling if \n the tool deduces that profiling is required during migration, else not).
```

2024-02-28 06:22 UTC, tomflinda commented on clang/include/clang/DPCT/DPCTOptions.inc
> +                   "auto\n(auto: mean off: if tool concludes profiling is not "
Updated.

2024-02-29 07:07 UTC, zhimingwang36 approved these changes
LGTM

2024-02-29 07:09 UTC, merged