[NFC][SYCLomatic] Use bitfield to reduce 16 bytes class size
oneapi-src/SYCLomatic pull request #1783
Opened 2024-03-13 08:53 UTC by yihanwg

2024-03-13 09:05 UTC, tangjj11 requested changes

2024-03-13 09:05 UTC, tangjj11 commented on clang/lib/DPCT/AnalysisInfo.h
> +  unsigned IsPseudo : 1;
declare but not use?

2024-03-13 09:10 UTC, yihanwg commented on clang/lib/DPCT/AnalysisInfo.h
> +  unsigned IsPseudo : 1;
removed

2024-03-13 09:13 UTC, tangjj11 approved these changes

2024-03-14 01:47 UTC, zhimingwang36 approved these changes
LGTM

2024-03-14 01:48 UTC, merged