Added migration support for add_library and add_link_options CMake syntaxes
oneapi-src/SYCLomatic pull request #1815
Opened 2024-03-24 14:38 UTC by TejaX-Alaghari

This PR adds migration support for add_library and add_link_options CMake syntaxes

2024-03-25 02:53 UTC, tomflinda requested changes
Pls rebase your PR to fix conflicts

2024-03-25 06:33 UTC, tomflinda commented on clang/lib/DPCT/PatternRewriter.cpp
> +
The fixing PR https://github.com/oneapi-src/SYCLomatic/pull/1813 has been merged, pls rebase your PR to latest SYCLomatic branch.

2024-03-25 06:50 UTC, zhiweij1 commented on clang/test/dpct/cmake_migration/case_037/expected.txt
> +add_link_options("--no-ptxas-options")
Is "--no-ptxas-options" an nvcc option? If so, can we remove it?

2024-03-26 02:19 UTC, zhiweij1 approved these changes

2024-03-26 08:41 UTC, tomflinda approved these changes
LGTM

2024-04-03 05:20 UTC, zhimingwang36 commented
Please solve the conflict.

2024-04-09 00:34 UTC, zhimingwang36 approved these changes
LGTM

2024-04-09 00:35 UTC, merged