[WIP][SYCLomatic] Support migration of 4 asm instructions
oneapi-src/SYCLomatic pull request #1840
Opened 2024-03-28 12:43 UTC by yihanwg

2024-04-09 03:34 UTC, tangjj11 requested changes

2024-04-09 03:34 UTC, tangjj11 commented on clang/lib/DPCT/APINames_ASM.inc
> +ENTRY("cvt", "cvt", true, NO_FLAG, P1, "Partial")
need test

2024-04-09 03:34 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmParser.cpp
> +      .Case("__nv_bfloat16", getBuiltinType(InlineAsmBuiltinType::TK_bf16))
```suggestion
      .Case("__nv_bfloat16", getBuiltinType(InlineAsmBuiltinType::TK_bf16))
      .Case("__nv_bfloat16_raw", getBuiltinType(InlineAsmBuiltinType::TK_bf16))
```

2024-04-09 03:34 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmParser.cpp
> +      .Case("__nv_bfloat162", getBuiltinType(InlineAsmBuiltinType::TK_bf16x2))
```suggestion
      .Case("__nv_bfloat162", getBuiltinType(InlineAsmBuiltinType::TK_bf16x2))
      .Case("__nv_bfloat162_raw", getBuiltinType(InlineAsmBuiltinType::TK_bf16x2))
```

2024-04-11 01:12 UTC, zhimingwang36 approved these changes
LGTM

2024-04-11 01:16 UTC, tangjj11 approved these changes

2024-04-12 01:04 UTC, merged