[SYCLomatic] Support migration of cub::DeviceSpmv::CsrMV
oneapi-src/SYCLomatic pull request #2007
Opened 2024-05-22 03:19 UTC by yihanwg

2024-05-22 06:09 UTC, zhiweij1 approved these changes

2024-05-22 06:13 UTC, tangjj11 requested changes

2024-05-22 06:13 UTC, tangjj11 commented on clang/lib/DPCT/Rewriters/CUB/RewriterDeviceSpmv.cpp
> +//===--------------- RewriterDeviceSelect.cpp -----------------------------===//
```suggestion
//===--------------- RewriterDeviceSpmv.cpp -----------------------------===//
```

2024-05-22 06:13 UTC, tangjj11 commented on clang/runtime/dpct-rt/include/dpct/sparse_utils.hpp
> +/// \param [in] num_rows Number of rows of the matrix A.
the param order is wrong

2024-05-22 07:24 UTC, yihanwg commented on clang/lib/DPCT/Rewriters/CUB/RewriterDeviceSpmv.cpp
> +//===--------------- RewriterDeviceSelect.cpp -----------------------------===//
fixed

2024-05-22 07:24 UTC, yihanwg commented on clang/runtime/dpct-rt/include/dpct/sparse_utils.hpp
> +/// \param [in] num_rows Number of rows of the matrix A.
fixed

2024-05-22 08:48 UTC, tangjj11 approved these changes

2024-05-31 08:15 UTC, zhimingwang36 approved these changes

2024-05-31 08:15 UTC, merged