[SYCLomatic] Support migration of ld and st instructions
oneapi-src/SYCLomatic pull request #2054
Opened 2024-06-12 08:01 UTC by yihanwg

2024-07-12 05:47 UTC, tangjj11 requested changes

2024-07-12 05:47 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmNodes.cpp
> +//===---------------------------- InlineAsm.cpp -----------------*- C++ -*-===//
```suggestion
//===---------------------------- AsmNodes.cpp
 -----------------*- C++ -*-===//
```

2024-07-12 05:47 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmNodes.cpp
> +// PTXNamedDecl::~PTXNamedDecl() = default;
what is this line.

2024-07-12 05:47 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmNodes.h
> +//===---------------------------- InlineAsm.h -------------------*- C++ -*-===//
```suggestion
//===---------------------------- AsmNodes.h -------------------*- C++ -*-===//
```

2024-07-12 05:47 UTC, tangjj11 commented on clang/lib/DPCT/Asm/AsmNodes.h
> +#ifndef CLANG_DPCT_INLINE_ASM_H
use wrong macro name.

2024-07-12 06:14 UTC, yihanwg commented on clang/lib/DPCT/Asm/AsmNodes.cpp
> +//===---------------------------- InlineAsm.cpp -----------------*- C++ -*-===//
done

2024-07-12 06:14 UTC, yihanwg commented on clang/lib/DPCT/Asm/AsmNodes.cpp
> +// PTXNamedDecl::~PTXNamedDecl() = default;
removed

2024-07-12 06:14 UTC, yihanwg commented on clang/lib/DPCT/Asm/AsmNodes.h
> +//===---------------------------- InlineAsm.h -------------------*- C++ -*-===//
done

2024-07-12 06:14 UTC, yihanwg commented on clang/lib/DPCT/Asm/AsmNodes.h
> +#ifndef CLANG_DPCT_INLINE_ASM_H
done

2024-07-12 06:18 UTC, tangjj11 approved these changes

2024-07-15 06:50 UTC, zhimingwang36 commented on clang/test/dpct/asm/st.cu
> +  asm volatile ("st.global.s32 [%0], %1;" :: "l"(a), "r"(111));
could you list all kind of the test that not support yet as test without checking,  then it easy to understand what is not supported yet. (try to understand what the "partial" mean in inc file.)

2024-07-23 06:10 UTC, yihwang-nv commented on clang/test/dpct/asm/st.cu
> +  asm volatile ("st.global.s32 [%0], %1;" :: "l"(a), "r"(111));
added

2024-07-26 02:31 UTC, zhimingwang36 approved these changes

2024-07-26 02:32 UTC, merged