[SYCLomatic] Analyze callee's qualifier
oneapi-src/SYCLomatic pull request #2081
Opened 2024-06-21 08:23 UTC by yihanwg

2024-06-21 08:30 UTC, tangjj11 requested changes

2024-06-21 08:30 UTC, tangjj11 commented on clang/test/dpct/analyze-callee.cu
> +// RUN: FileCheck %s --match-full-lines --input-file %T/analyze-callee/analyze-callee.dp.cpp
Need build.

2024-06-21 08:32 UTC, yihanwg commented on clang/test/dpct/analyze-callee.cu
> +// RUN: FileCheck %s --match-full-lines --input-file %T/analyze-callee/analyze-callee.dp.cpp
done

2024-06-21 08:33 UTC, tangjj11 approved these changes

2024-06-21 08:36 UTC, ziranzha approved these changes

2024-06-24 07:24 UTC, zhimingwang36 approved these changes

2024-06-24 07:33 UTC, merged