[SYCLomatic] Support migration of cub::{LoadDirectBlocked, LoadDirectStriped}
oneapi-src/SYCLomatic pull request #2094
Opened 2024-06-26 07:10 UTC by yihanwg

2024-06-26 07:14 UTC, tangjj11 requested changes

2024-06-26 07:14 UTC, tangjj11 commented on clang/lib/DPCT/APINames_CUB.inc
> +ENTRY(cub::LoadDirectStriped, cub::LoadDirectStriped, true, NO_FLAG, P4, "Comment")
```suggestion
ENTRY(cub::LoadDirectStriped, cub::LoadDirectStriped, true, NO_FLAG, P4, "Successful")
```

2024-06-26 07:16 UTC, yihanwg commented on clang/lib/DPCT/APINames_CUB.inc
> +ENTRY(cub::LoadDirectStriped, cub::LoadDirectStriped, true, NO_FLAG, P4, "Comment")
done

2024-06-26 07:16 UTC, tangjj11 approved these changes

2024-07-11 05:17 UTC, abhilash1910 reviewed
LGTM! Thanks

2024-08-02 01:58 UTC, ziranzha requested changes
Should keep backward compatibility.

2024-08-14 01:52 UTC, ziranzha approved these changes

2024-08-14 01:53 UTC, merged