[SYCLomatic] Enable Migration of meta_group_size()
oneapi-src/SYCLomatic pull request #2382
Opened 2024-09-26 09:07 UTC by abhilash1910

Used in llm.c 
warp.meta_group_size()
cc @ShengchenJ  @zhimingwang36 @yihanwg

2024-09-27 00:46 UTC, ShengchenJ approved these changes
LGTM

2024-10-25 07:55 UTC, ShengchenJ approved these changes

2024-11-06 08:49 UTC, zhimingwang36 approved these changes

2024-11-18 03:32 UTC, ShengchenJ approved these changes

2024-11-26 08:49 UTC, ShengchenJ requested changes

2024-11-26 08:49 UTC, ShengchenJ commented on clang/test/dpct/cooperative_groups2.cu
> +  // CHECK: atile2.get_local_linear_range();
the meta_group_size means the group number after the partition in the CUDA docs(https://docs.nvidia.com/cuda/cuda-c-programming-guide/#coalesced-groups)  but get_local_linear_range means the size of the work items in partitioned group.

2024-11-26 09:16 UTC, abhilash1910 commented on clang/test/dpct/cooperative_groups2.cu
> +  // CHECK: atile2.get_local_linear_range();
Yes mapping is changed. Please review , thanks

2024-11-28 02:30 UTC, merged

2024-11-28 02:30 UTC, ShengchenJ approved these changes