[SYCLomatic][DOC][NFC] Merge GetStartedGuide.md into README.md.
oneapi-src/SYCLomatic pull request #282
Opened 2022-10-11 11:03 UTC by zhimingwang36

2022-10-11 19:32 UTC, YuriPlyakhin requested changes
How about adding table of contents, since the readme is quite big now?

2022-10-11 19:44 UTC, YuriPlyakhin requested changes

2022-10-11 19:44 UTC, YuriPlyakhin commented on README.md
> +#### Create SYCLomatic workspace
```suggestion
### Create SYCLomatic workspace
```

2022-10-11 19:44 UTC, YuriPlyakhin commented on README.md
> +#### Deployment
```suggestion
### Deployment
```

2022-10-11 19:44 UTC, YuriPlyakhin commented on README.md
>  * [SYCLomatic getting started](GetStartedGuide.md)
```suggestion
```

2022-10-12 01:38 UTC, zhimingwang36 commented
> How about adding table of contents, since the readme is quite big now?

done.

2022-10-12 01:40 UTC, ziranzha approved these changes
LGTM

2022-10-12 01:52 UTC, merged