[SYCLomatic] Fix the bug that cannot be assigned from dpct::device_vector to std::vector
oneapi-src/SYCLomatic pull request #403
Opened 2022-12-08 05:30 UTC by wenhuiNi

Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

2022-12-14 01:22 UTC, ziranzha approved these changes
LGTM

2022-12-14 12:21 UTC, timmiesmith requested changes

2022-12-14 12:21 UTC, timmiesmith commented on clang/runtime/dpct-rt/include/dpl_extras/vector.h.inc
> +  template <typename OtherA> operator std::vector<T, OtherA>() const {
The same change is needed on line 445 to keep the device_vector behavior consistent in USM and non-USM cases.

2022-12-14 12:21 UTC, timmiesmith commented on clang/test/dpct/helper_files_ref/include/dpl_extras/vector.h
> +  template <typename OtherA> operator std::vector<T, OtherA>() const {
The same change is needed on line 390 to keep the device_vector behavior consistent in USM and non-USM cases.

2022-12-27 06:21 UTC, zhimingwang36 approved these changes
LGTM

2022-12-27 06:22 UTC, merged