[SYCLomatic] Rename APINames*.inc files
oneapi-src/SYCLomatic pull request #447
Opened 2022-12-27 02:23 UTC by yihanwg

Signed-off-by: Wang, Yihan <yihan.wang@intel.com>

2022-12-27 05:42 UTC, zhimingwang36 requested changes
The 1st line of the *inc files contains old filename should be updated. 

E.g. :  //===--------------- APINamesCooperativeGroups.inc ------------------------===// 
the APINamesCooperativeGroups.inc should be updated with the new filename.

2022-12-27 08:00 UTC, yihanwg commented
> The 1st line of the *inc files contains old filename should be updated.
> 
> E.g. : //===--------------- APINamesCooperativeGroups.inc ------------------------===// the APINamesCooperativeGroups.inc should be updated with the new filename.

done

2023-01-17 00:55 UTC, yihanwg commented on clang/lib/DPCT/Rewriters/CUFFT/CallExprRewriterCUFFT.cpp
> +//===--------------- .cpp ----------------------------===//
//===--------------- CallExprRewriterCUFFT.cpp ----------------------------===//

2023-03-13 01:53 UTC, yihanwg commented on clang/lib/DPCT/Rewriters/CUFFT/CallExprRewriterCUFFT.cpp
> +//===--------------- .cpp ----------------------------===//
done

2023-03-14 01:41 UTC, AndyCHHuang commented on clang/lib/DPCT/Rewriters/CooperativeGroups/CallExprRewriterCG.inc
> +//===--------------- CallExprRewriterCG.inc.inc ---------------------------===//
deplicate inc

2023-03-14 01:48 UTC, yihanwg commented on clang/lib/DPCT/Rewriters/CooperativeGroups/CallExprRewriterCG.inc
> +//===--------------- CallExprRewriterCG.inc.inc ---------------------------===//
done

2023-03-14 01:49 UTC, AndyCHHuang approved these changes
LGTM

2024-01-30 06:56 UTC, closed without merging