[SYCLomatic] Support the migration of 4 CUB api
oneapi-src/SYCLomatic pull request #454
Opened 2022-12-28 11:05 UTC by yihanwg

- cub::DeviceScan::InclusiveScanByKey
- cub::DeviceScan::InclusiveSumByKey
- cub::DeviceScan::ExclusiveScanByKey
- cub::DeviceScan::ExclsuvieSumByKey

Signed-off-by: Wang, Yihan <yihan.wang@intel.com>

2022-12-29 05:39 UTC, AndyCHHuang requested changes

2022-12-29 05:39 UTC, AndyCHHuang commented on clang/lib/DPCT/CallExprRewriter.h
> +/// Print a `type`. This is useful when print no template type.
Print a type with no template.

2022-12-30 01:35 UTC, yihanwg commented on clang/lib/DPCT/CallExprRewriter.h
> +/// Print a `type`. This is useful when print no template type.
done

2023-01-03 03:00 UTC, AndyCHHuang approved these changes
LGTM

2023-01-03 08:30 UTC, zhimingwang36 approved these changes
LGTM

2023-01-03 08:30 UTC, merged