[SYCLomatic] Use rewriter to migrate 4 APIs to fix incorrect migration when API is in macro
oneapi-src/SYCLomatic pull request #49
Opened 2022-05-30 10:05 UTC by zhiweij1

Covered APIs:
cudaGetErrorString
cudaGetErrorName
cudaGetLastError
cudaPeekAtLastError

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2022-05-31 08:27 UTC, AndyCHHuang requested changes

2022-05-31 08:27 UTC, AndyCHHuang commented on clang/test/dpct/cuda-get-error-string.cu
> +//CHECK-NEXT:  return "cudaGetErrorName not supported"/*cudaGetErrorName(cudaSuccess)*/;
"is" not supported

2022-06-01 00:30 UTC, zhiweij1 commented on clang/test/dpct/cuda-get-error-string.cu
> +//CHECK-NEXT:  return "cudaGetErrorName not supported"/*cudaGetErrorName(cudaSuccess)*/;
done

2022-06-01 00:32 UTC, AndyCHHuang approved these changes

2022-06-01 00:59 UTC, ziranzha commented on clang/lib/DPCT/CallExprRewriter.cpp
> +template <class T>
This overload can be removed

2022-06-01 00:59 UTC, ziranzha commented on clang/lib/DPCT/CallExprRewriter.cpp
> +  createInsertAroundFactory(x PREFIX, SUFFIX, 0),
', 0' is not needed.

2022-06-01 01:11 UTC, zhiweij1 commented on clang/lib/DPCT/CallExprRewriter.cpp
> +template <class T>
done

2022-06-01 01:11 UTC, zhiweij1 commented on clang/lib/DPCT/CallExprRewriter.cpp
> +  createInsertAroundFactory(x PREFIX, SUFFIX, 0),
done

2022-06-01 06:29 UTC, ziranzha approved these changes
LGTM

2022-06-01 06:30 UTC, merged