[SYCLomatic] Fix habs lit test errors
oneapi-src/SYCLomatic pull request #50
Opened 2022-05-30 22:42 UTC by 0x12CC

Moves lit tests for the `__habs` and `__habs2` functions into a separate file since they're unsupported in CUDA versions earlier than v10.2.

2022-05-31 07:34 UTC, zhiweij1 approved these changes

2022-06-01 02:28 UTC, AndyCHHuang approved these changes

2022-06-01 02:28 UTC, ziranzha approved these changes

2022-06-01 02:30 UTC, ziranzha requested changes
Need sign off commit.

2022-06-06 00:53 UTC, zhimingwang36 approved these changes

2022-06-06 00:53 UTC, merged