[SYCLomatic]Optimize the compilation experience when modifying help_functions
oneapi-src/SYCLomatic pull request #522
Opened 2023-01-29 06:53 UTC by wenhuiNi

Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

2023-01-29 07:49 UTC, tangjj11 requested changes

2023-01-29 07:49 UTC, tangjj11 commented on clang/runtime/dpct-rt/include/processFiles.py
> +        if(content_str != features_enum_str):
need format.

2023-01-29 07:50 UTC, tangjj11 approved these changes

2023-01-30 01:04 UTC, zhiweij1 approved these changes

2023-02-07 01:58 UTC, zhimingwang36 approved these changes
LGTM

2023-02-07 02:00 UTC, merged