[SYCLomatic] Refine migration of CuDNN types
oneapi-src/SYCLomatic pull request #533
Opened 2023-01-31 23:27 UTC by jzc

Signed-off-by: Cai, Justin <justin.cai@intel.com>

2023-02-02 21:59 UTC, 0x12CC approved these changes

2023-02-08 07:36 UTC, ziranzha commented
Please ask @intwanghao for approval.

2023-02-14 08:43 UTC, intwanghao commented on clang/test/dpct/dnn/types.cu
> +  // CHECK-NEXT: if (true) {
I think use operator= overload and user defined conversion function is a better solution.
Just like:
operator=(std::nullptr_t ptr){
 set the _q to null and clear worksapce
}
and 
operator bool(){
 return q == nullptr;
}

2023-02-16 08:47 UTC, intwanghao approved these changes
LGTM

2023-02-16 16:15 UTC, 0x12CC requested changes

2023-02-16 16:15 UTC, 0x12CC commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  operator bool() {
```suggestion
  operator bool() const {
```

2023-02-16 16:15 UTC, 0x12CC commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  operator bool() {
```suggestion
  operator bool() const {
```

2023-02-16 16:15 UTC, 0x12CC commented on clang/runtime/dpct-rt/include/dnnl_utils.hpp.inc
> +  operator bool() {
```suggestion
  operator bool() const {
```

2023-02-16 16:50 UTC, 0x12CC approved these changes

2023-02-17 15:59 UTC, merged