[CI]designate CUDA version when run lit in gh actions
oneapi-src/SYCLomatic pull request #60
Opened 2022-06-06 02:13 UTC by DoyleLi

Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>

2022-06-06 08:01 UTC, delecui requested changes

2022-06-06 08:01 UTC, delecui commented on .github/workflows/ci_win.yml
>            ninja check-clang-c2s -j8
Windows "Lit" runs with CUDA 10.2. This is different from Linux "Lit", which runs with CUDA 11.6. 
Please investigate to fix it or set CUDA_PATH to 11.6 explicitly as temporary workaround.

2022-06-06 08:01 UTC, delecui commented on .github/workflows/ci_win.yml
> +          set CUDA_PATH="L:/ref/cuda/win/v8.0" && ninja check-clang-c2s -j8
`set CUDA_PATH="L:/ref/cuda/win/vM.N"` does not seems to work. CUDA 10.2 is still used.

Suggest you remove the quotes and have a try.

2022-06-09 05:59 UTC, DoyleLi commented
Hi @delecui and @zhimingwang36, the patch to enable Lit for different CUDA versions is ready. Please help to approve and merge the PR, thanks!

2022-06-09 06:07 UTC, delecui approved these changes
LGTM

2022-06-10 07:46 UTC, DoyleLi commented
@zhimingwang36  could you please help to approve and merge the PR? Thank you!

2022-06-13 01:35 UTC, zhimingwang36 approved these changes, later dismissed
LGTM

2022-06-15 00:48 UTC, DoyleLi commented
@zhimingwang36 Ping.

2022-06-15 06:34 UTC, zhimingwang36 approved these changes
LGTM

2022-06-15 06:39 UTC, merged