[DOC] Add API migration status page
oneapi-src/SYCLomatic pull request #606
Opened 2023-02-16 22:17 UTC by krisdale

Add new API migration status page that lists the status of migration support for CUDA APIs.

Additionally includes refactor of DPCT page IDs for simple links from migration status tables.

2023-02-17 00:39 UTC, jiejanezhang approved these changes

2023-02-21 05:51 UTC, zhimingwang36 commented
@krisdale *inc files in SYCLomatic are updated,  so please update the PR based on latest files from @wenhuiNi .  Thanks.

2023-02-28 00:15 UTC, zhimingwang36 commented on docs/dev_guide/api-mapping-status/Runtime_and_Driver_API_migration_status.csv
> +cuMemGetInfo,NO,
1. L1545 is duplicated with L1163, Please remove L1545.

2023-02-28 00:17 UTC, zhimingwang36 commented on docs/dev_guide/api-mapping-status/Runtime_and_Driver_API_migration_status.csv
> +cuMemGetInfo,YES,:ref:`DPCT1106`
besides DPCT1106,  also add: DPCT1072 for line 1163.

2023-02-28 00:17 UTC, zhimingwang36 requested changes
two small change required.

2023-02-28 00:56 UTC, zhimingwang36 approved these changes
LGTM

2023-02-28 00:57 UTC, merged