[SYCLomatic][NFC] Update math and nvrrtc in APINames.inc to cuda-12.0
oneapi-src/SYCLomatic pull request #631
Opened 2023-02-21 03:12 UTC by wenhuiNi

Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

2023-02-21 03:15 UTC, tangjj11 requested changes

2023-02-21 03:15 UTC, tangjj11 commented on clang/lib/DPCT/APINames.inc
> +ENTRY(_viaddmin_s16x2, _viaddmin_s16x2, false, NO_FLAG, P4, "comments")
need two '_'

2023-02-21 03:20 UTC, tangjj11 approved these changes

2023-02-21 03:21 UTC, zhiweij1 approved these changes

2023-03-06 06:05 UTC, zhimingwang36 approved these changes
LGTM

2023-03-06 06:05 UTC, merged