[SYCLomatic] Update exsisting warning messages (align between code and doc)
oneapi-src/SYCLomatic pull request #632
Opened 2023-02-21 03:12 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-02-21 08:27 UTC, zhimingwang36 approved these changes
LGTM

2023-02-21 08:28 UTC, zhimingwang36 commented
@krisdale , please review this PR.

2023-02-22 20:56 UTC, krisdale requested changes
A couple minor updates needed. Approved once the updates are made as I described.

2023-02-22 20:56 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1013.rst
> +functions rounding mode is aligned with OpenCL C 1.2 standard.
Update to "function" instead of functions.

2023-02-22 20:56 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1063.rst
> +Advice parameter is device-defined``<addtional action>``. You may need to adjust it.
Spelling error and spacing issue: Add space after device-defined and update spelling to "additional"

2023-02-23 02:01 UTC, zhimingwang36 approved these changes
LGTM

2023-02-23 02:16 UTC, merged