[SYCLomatic] Add new options and warning in doc folder
oneapi-src/SYCLomatic pull request #634
Opened 2023-02-21 05:44 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-02-21 08:58 UTC, zhimingwang36 approved these changes
LGTM

2023-02-22 20:50 UTC, krisdale requested changes
Editorial review completed for existing content. 

Before merging, dpct message detail pages need to be completed (addition of Detailed Help and Suggestions to Fix sections).

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +     - Enables sycl queue profiling in helper functions. Default: off.
Update to "Enable SYCL queue ..."

Formatting for rendered docs: Add double back ticks (``) default value (off).

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +     - A comma separated list of extensions not to be used in migrated code.
"comma-separated" is correct and already in use in multiple locations in the doc. Lets stay consistent using "comma-separated".

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +     - A comma separated list of extensions to be used in migrated code.
"comma-separated"

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +       - ``=device_info``: Use Intel's Extensions for Device Information if it is
Update to "Use the Intel extensions for device information if supported ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +       - ``=c_cxx_standard_library``: Use std functions from libdevice (provided by
Update to "... from the libdevice library ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +         functions which has no mapping in SYCL standard.
update to "... which have no mapping in the SYCL..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +         If this value is used together with intel_device_math, intel_device_math
Update to "If this value is used together with intel_device_math, the intel_device_math ..."

Formatting for rendered docs: Add double back ticks (``) around function names/namespace.

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +       - ``=intel_device_math``: Use sycl::ext::intel::math functions from libdevice
Update to " ... from the libdevice library .."

Formatting for rendered docs: Add double back ticks (``) around function names/namespace.

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +         have no mapping in SYCL standard.
"... in the SYCL .."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1103.rst
> +"wrapped" kernel functions.
Update to "... supply wrapped kernel ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1104.rst
> +library should supply "wrapped" kernel functions.
Update to "... supply wrapped kernel ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1105.rst
> +library should supply "wrapped" kernel functions. Compilation options passed to
Update to "... supply wrapped kernel ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1106.rst
> +``<function name>`` was migrated with Intel's Extensions for Device Information which
Update to "... with the Intel extensions for device information ..."

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +         Intel(R) oneAPI DPC++/C++ Compiler) and C/C++ standard library to migrate
"C/C++ Standard Library"

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +     - Limit extension change to .cu and .cuh files only. Default: off.
Formatting for rendered docs: Add double back ticks (``) around file extensions (.cu, .cuh) and default value (off).

2023-02-22 20:50 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1105.rst
> +cuModuleLoadDataEx are not migrated.
Formatting for rendered docs: Add double back ticks (``) around function names.

2023-02-23 22:07 UTC, krisdale requested changes
Overall looks good. I made some suggestions for both grammar and to be consistent with patterns in use in existing docs.  In general, make sure to have a line between the end of a code block and the following text (Sphinx is sensitive to whitespace and lines between content blocks). 

If you apply these changes, I approve.

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1101.rst
> +Identities including constant variable name(s), type(s) and macro(s) used in the
Small edit: add comma after "type(s)"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1101.rst
> +Use macro or const variable to replace the value.
"Use **a** macro or ..."

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1101.rst
> +Original code:
Replace with: "For example, this original CUDA* code:

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1101.rst
> +Migrated code:
Replace with: "results in the following migrated SYCL code:"

(And make sure there is a return line between the code block and text)

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1101.rst
> +Fixed code:
Replace with : "which is rewritten to:"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1102.rst
> +Zero-length arrays are not supported in C++ standard and SYCL Spec. It may be
"... in the C++ standard or SYCL specification."

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1102.rst
> +Intel(R) oneAPI DPC++/C++ Compiler for device code.
Use "®"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1102.rst
> +Use array which length is greater than zero.
"Use an array with length greater than..."

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1102.rst
> +Example:
Follow the same pattern with the example code as I showed in dpct1101. 

"For example, this original CUDA* code:"
[original code block]

"results in the following migrated SYCL code:"
[migrated code block]

"which is rewritten to:"
[rewritten code block]

This pattern is already in place, as seen in the existing doc for DPCT1086.

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1103.rst
> +The CUDA application expects ``<expression text>`` to be the name of a CUDA module.
"The CUDA*..."

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1103.rst
> +and migrate them to SYCL with the --extra-arg=-ptx option of the compatibility tool
"... migrate them to SYCL using the .."

and wrap the option in double back ticks (``)

Replace "compatibility tool" with "|tool_name|"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1103.rst
> +Example:
Please apply the same pattern as I described in dpct1101 and dpct1102

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1104.rst
> +The CUDA application expects ``<expression text>`` to point to a CUDA module whose file
"The CUDA* ..."

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1104.rst
> +migrate the module source file(s) to SYCL with the --extra-arg=--ptx option of the
"... to SYCL using the ..."

Wrap option in double back ticks (``)

Replace "compatibility tool" with "|tool_name|"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1104.rst
> +Example:
Please apply the same pattern as described in dpct1101.

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1106.rst
> +by all compilers or runtimes.
"The **CUDA*** **function** ``<function name>`` (for example ``cudaMemGetInfo`` or ``cuMemGetInfo``) was
 migrated with **the** **Intel extensions for device information**, which may be not supported
 by all compilers or runtimes. **You may need to adjust the code.**"

2023-02-23 22:07 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1106.rst
> +Original code:
Please apply the same pattern as described in dpct1101.

2023-02-24 00:16 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1106.rst
> +may be not supported by all compilers or runtimes. You may need to adjust the code.
"... may not be supported ..."

2023-02-24 05:37 UTC, zhimingwang36 approved these changes
LGTM

2023-02-24 05:37 UTC, merged