[SYCLomatic] Add a new option in doc
oneapi-src/SYCLomatic pull request #635
Opened 2023-02-21 06:30 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-02-23 02:18 UTC, zhimingwang36 commented on docs/dev_guide/command-line-options-reference.rst
> +     - DEPRECATED: Specifies which extensions of migrated fileswill be changed,
```suggestion
     - DEPRECATED: Specifies which extension of migrated files will be changed,

```

2023-02-23 22:12 UTC, krisdale requested changes
Approved if the changes are applied.

2023-02-23 22:12 UTC, krisdale commented on docs/dev_guide/command-line-options-reference.rst
> +     - DEPRECATED: Specifies which extension(s) of migrated file(s) will be changed,
"DEPRECATED: A comma-separated list that specifies which extensions of migrated files will be changed. Default..."

2023-02-24 03:13 UTC, zhimingwang36 approved these changes
LGTM

2023-02-24 03:15 UTC, merged