[SYCLomatic] Migrate CU_JIT* options
oneapi-src/SYCLomatic pull request #641
Opened 2023-02-21 22:12 UTC by LU-JOHN

Migrate CU_JIT* options that are passed to cuLoadDataEx.

Signed-off-by: Lu, John [john.lu@intel.com](mailto:john.lu@intel.com)

2023-02-23 15:27 UTC, 0x12CC requested changes

2023-02-23 15:27 UTC, 0x12CC commented on clang/lib/DPCT/ASTTraversal.cpp
> +    auto *EC = cast<EnumConstantDecl>(DE->getDecl());
Can this declaration be removed?

2023-02-23 15:27 UTC, 0x12CC commented on clang/lib/DPCT/ASTTraversal.cpp
> +    return;
```suggestion
```

2023-02-23 15:27 UTC, 0x12CC commented on clang/lib/DPCT/ASTTraversal.cpp
> +                  "cudaDeviceAttr", "CUmodule", "CUjit_option", "CUfunction", "cudaMemcpyKind",
Use `clang-format` since this line now exceeds 80 columns.

2023-02-23 15:27 UTC, 0x12CC commented on clang/test/dpct/cu_jit.cu
> +}
```suggestion
}

```

2023-02-24 16:20 UTC, LU-JOHN commented on clang/lib/DPCT/ASTTraversal.cpp
> +    auto *EC = cast<EnumConstantDecl>(DE->getDecl());
EC removed

2023-02-24 16:20 UTC, LU-JOHN commented on clang/lib/DPCT/ASTTraversal.cpp
> +    return;
return unnecessary and removed

2023-02-24 16:20 UTC, LU-JOHN commented on clang/lib/DPCT/ASTTraversal.cpp
> +                  "cudaDeviceAttr", "CUmodule", "CUjit_option", "CUfunction", "cudaMemcpyKind",
reformatted

2023-02-24 16:20 UTC, LU-JOHN commented on clang/test/dpct/cu_jit.cu
> +}
done

2023-02-24 16:34 UTC, 0x12CC approved these changes

2023-02-24 16:40 UTC, jzc approved these changes

2023-02-24 16:41 UTC, merged