[SYCLomatic] Add migration for cusolverEigRange_t
oneapi-src/SYCLomatic pull request #651
Opened 2023-02-22 16:05 UTC by 0x12CC

Signed-off-by: Michael Aziz <michael.aziz@intel.com>

2023-02-22 22:57 UTC, jzc approved these changes

2023-02-24 19:36 UTC, LU-JOHN commented on clang/lib/DPCT/MapNames.cpp
> +      {"CUSOLVER_EIG_RANGE_I", std::make_shared<EnumNameRule>("'I'")},
Should we deal with the other CUSOLVER_EIG* values:

include/cusolver_common.h:    CUSOLVER_EIG_TYPE_1 = 1,
include/cusolver_common.h:    CUSOLVER_EIG_TYPE_2 = 2,
include/cusolver_common.h:    CUSOLVER_EIG_TYPE_3 = 3
include/cusolver_common.h:    CUSOLVER_EIG_MODE_NOVECTOR = 0,
include/cusolver_common.h:    CUSOLVER_EIG_MODE_VECTOR = 1
include/cusolver_common.h:    CUSOLVER_EIG_RANGE_ALL = 1001,
include/cusolver_common.h:    CUSOLVER_EIG_RANGE_I = 1002,
include/cusolver_common.h:    CUSOLVER_EIG_RANGE_V = 1003,

2023-02-24 19:40 UTC, 0x12CC commented on clang/lib/DPCT/MapNames.cpp
> +      {"CUSOLVER_EIG_RANGE_I", std::make_shared<EnumNameRule>("'I'")},
I don't think so, since the other values are not related to the range type. This PR only addresses values that are used in the context of a `cusolverEigRange_t`. The others may not yet have a meaningful mapping.

2023-02-25 04:44 UTC, LU-JOHN approved these changes

2023-02-25 09:56 UTC, zhimingwang36 commented on clang/test/dpct/cusolver_range.cu
> +  cusolverEigRange_t range = CUSOLVER_EIG_RANGE_ALL;
do you have  end 2 end test example to show the mapping is working and make sense?

2023-02-27 02:27 UTC, zhimingwang36 commented on clang/test/dpct/cusolver_range.cu
> +  cusolverEigRange_t range = CUSOLVER_EIG_RANGE_ALL;
is mapping  "cusolverEigRange_t map to int" better?

2023-02-27 02:44 UTC, zhiweij1 commented on clang/test/dpct/cusolver_range.cu
> +  range = CUSOLVER_EIG_RANGE_V;
I think there is mapping in oneMKL.
cusolverEigRange_t => oneapi::mkl::rangev
CUSOLVER_EIG_RANGE_ALL => oneapi::mkl::rangev::all
CUSOLVER_EIG_RANGE_V => oneapi::mkl::rangev::values
CUSOLVER_EIG_RANGE_I => oneapi::mkl::rangev::indices

2023-02-27 02:48 UTC, zhiweij1 commented on clang/test/dpct/cusolver_range.cu
> +  cusolverEigRange_t range = CUSOLVER_EIG_RANGE_ALL;
```suggestion
  oneapi::mkl::rangev range = oneapi::mkl::rangev::all;
```

2023-02-27 02:48 UTC, zhiweij1 commented on clang/test/dpct/cusolver_range.cu
> +  range = CUSOLVER_EIG_RANGE_V;
```suggestion
  range = oneapi::mkl::rangev::values;
```

2023-02-27 02:48 UTC, zhiweij1 commented on clang/test/dpct/cusolver_range.cu
> +  range = CUSOLVER_EIG_RANGE_I;
```suggestion
  range = oneapi::mkl::rangev::indices;
```

2023-02-27 02:49 UTC, zhiweij1 requested changes
I think there are available mappings in oneMKL.
cusolverEigRange_t => oneapi::mkl::rangev
CUSOLVER_EIG_RANGE_ALL => oneapi::mkl::rangev::all
CUSOLVER_EIG_RANGE_V => oneapi::mkl::rangev::values
CUSOLVER_EIG_RANGE_I => oneapi::mkl::rangev::indices

2023-02-27 16:51 UTC, 0x12CC commented on clang/test/dpct/cusolver_range.cu
> +  cusolverEigRange_t range = CUSOLVER_EIG_RANGE_ALL;
The PR for end-to-end testing is here: https://github.com/oneapi-src/SYCLomatic-test/pull/241. This test case ensures that the migrated code can be compiled. It doesn't execute the migrated program since we don't yet migrate any functions that use this type.

I used `char` since that's the type in the MKL C interface: https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem/lapack-least-squares-eigenvalue-problem-driver/symmetric-eigenvalue-problems-lapack-driver/syevx.html. I've since updated-it to `oneapi::mkl::rangev` based on @zhiweij1's suggeestion.

2023-02-28 00:20 UTC, zhiweij1 approved these changes

2023-03-01 00:07 UTC, merged