[SYCLomatic][DOC] Update DPCT1051 message in doc
oneapi-src/SYCLomatic pull request #657
Opened 2023-02-23 02:38 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-02-23 21:30 UTC, krisdale requested changes
Small edits for readability - approved with the edits applied.

2023-02-23 21:30 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1051.rst
> +SYCL does not support the device property functionally compatible with *<property name>*.
Minor edit (reads a little better): "SYCL does not support **a** device property functionally compatible ..."

2023-02-23 21:30 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1051.rst
> +It was migrated to *<migrated token>*, which value may need to be adjusted for
Update to: "It was migrated to <migrated token>. You may need to adjust the value of <migrated token> for the specific device."

2023-02-24 03:25 UTC, zhimingwang36 approved these changes
LGTM

2023-02-24 03:25 UTC, merged