[SYCLomatic][DOC] Update DPCT1028 "Detailed Help" and "Suggestions to Fix" in doc
oneapi-src/SYCLomatic pull request #695
Opened 2023-03-02 02:25 UTC by zhiweij1

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

2023-03-02 02:28 UTC, zhimingwang36 approved these changes
LGTM

2023-03-02 21:31 UTC, krisdale requested changes
Approved if the requested changes are implemented.

2023-03-02 21:31 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1028.rst
> +If the parameter is a CUDA\* device attribute:
remove "\*" (only need to use attribution on first use in page).

2023-03-02 21:31 UTC, krisdale commented on docs/dev_guide/diagnostic_ref/dpct1028.rst
> +Redesign the code logic to get rid of the usage of the device attribute.
"Redesign the code logic to remove use of the device attribute."

2023-03-03 01:41 UTC, zhimingwang36 approved these changes

2023-03-03 01:41 UTC, merged