[SYCLomatic] Fix incorect migration of thrust::remove_copy_if when it is called in a template function
oneapi-src/SYCLomatic pull request #711
Opened 2023-03-06 07:46 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2023-03-06 15:42 UTC, 0x12CC requested changes

2023-03-06 15:42 UTC, 0x12CC commented on clang/test/dpct/thrust_template.cu
> +
```suggestion
#include <thrust/unique.h>

```

2023-03-07 00:26 UTC, tomflinda commented on clang/test/dpct/thrust_template.cu
> +
ok

2023-03-07 06:15 UTC, zhiweij1 approved these changes

2023-03-08 09:08 UTC, zhimingwang36 approved these changes
LGTM

2023-03-08 09:10 UTC, merged