[SYCLomatic] Refine the mapping for thrus::for_each with nosync policy
oneapi-src/SYCLomatic pull request #726
Opened 2023-03-08 02:22 UTC by wenhuiNi

Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

2023-03-08 07:20 UTC, zhiweij1 commented on clang/include/clang/DPCT/DPCTOptions.inc
> +             DPCT_OPT_ENUM("DPL_async", int(ExperimentalFeatures::Exp_DPLAsync),
How about async-dpl-algorithm?

2023-03-08 07:23 UTC, zhiweij1 commented on clang/test/dpct/thrust-for-each-nosync.cu
> +// UNSUPPORTED: cuda-8.0, cuda-9.0
I think the code can be simplified since this case only focus on the migration of `thrust::for_each(thrust::cuda::par_nosync, ...)`.

2023-03-08 07:24 UTC, zhiweij1 commented on clang/lib/DPCT/APINamesThrust.inc
> +                                               "thrust::cuda_cub::par_nosync"),
What will happen if the type of argument 0 cannot be deduced during migration?

2023-03-08 07:31 UTC, zhiweij1 requested changes
The code style of the new value needs to be aligned with the existing ones.
LIT case can be simplified.

2023-03-08 08:10 UTC, zhiweij1 approved these changes

2023-03-09 06:53 UTC, ziranzha approved these changes

2023-03-10 02:48 UTC, zhimingwang36 commented on clang/include/clang/DPCT/DPCTOptions.inc
> +             DPCT_OPT_ENUM("async-dpl-algorithm", int(ExperimentalFeatures::Exp_AsyncDPLAlgorithm),
Let's use one option to control using of APIs from oneapi::dpl::experimental for dpl.  so please update the option name and desc.

2023-03-15 12:58 UTC, LU-JOHN approved these changes

2023-03-21 02:31 UTC, zhimingwang36 commented on clang/include/clang/DPCT/DPCTOptions.inc
> +        "Experimental extension that allows oneDPL experimental API.\n",
```suggestion
        "Experimental extension that allows oneDPL experimental API.\n",
```
```suggestion
        "Experimental extension that allows oneDPL experimental API during migration.\n",
```

2023-03-21 02:35 UTC, zhimingwang36 approved these changes
LGTM

2023-03-21 02:39 UTC, merged