[SYCLomatic] Migrate device ID and UUID
oneapi-src/SYCLomatic pull request #732
Opened 2023-03-09 18:48 UTC by 0x12CC

Signed-off-by: Michael Aziz <michael.aziz@intel.com>

2023-03-09 18:54 UTC, 0x12CC commented
End-to-end tests: https://github.com/oneapi-src/SYCLomatic-test/pull/256

2023-03-10 00:50 UTC, tomflinda requested changes
Hi @0x12CC, the migration of device ID and UUID should follow the same way of migrating cudaMemGetInfo(), which also uses Intel's Extensions for Device Information "sycl::ext::intel::info::device::free_memory", and the behavior is controlled by option "--no-dpcpp-extensions=device_info".

2023-03-14 00:30 UTC, zhiweij1 approved these changes

2023-03-14 00:30 UTC, tomflinda approved these changes
LGTM

2023-03-14 13:57 UTC, merged