[SYCLomatic] Fix 2 cub lit test compile fail
oneapi-src/SYCLomatic pull request #765
Opened 2023-03-23 04:43 UTC by yihanwg

2023-03-23 20:25 UTC, jzc requested changes

2023-03-23 20:25 UTC, jzc commented on clang/test/dpct/cub/devicelevel/arg_index_iterator.o
Looks like this object file was accidentally committed.

2023-03-24 01:09 UTC, yihanwg commented on clang/test/dpct/cub/devicelevel/arg_index_iterator.o
Good catch! I have removed this object file, thanks a lot!

2023-03-24 05:13 UTC, wenhuiNi approved these changes

2023-03-24 05:15 UTC, tangjj11 approved these changes

2023-03-24 08:47 UTC, zhiweij1 approved these changes

2023-03-28 15:03 UTC, zhimingwang36 approved these changes
LGTM

2023-03-28 15:04 UTC, merged