[SYCLomatic] Support migration of thrust::uninitialized_copy
oneapi-src/SYCLomatic pull request #947
Opened 2023-05-26 05:38 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2023-05-30 00:25 UTC, zhiweij1 requested changes

2023-05-30 00:25 UTC, zhiweij1 commented on clang/test/dpct/thrust-algo.cu
> +  int array[N];
Redeclared. Previous declaration at line 1137

2023-05-30 00:25 UTC, zhiweij1 commented on clang/test/dpct/thrust-algo.cu
> +  int array[N];
Redeclared. Previous declaration at line 1118

2023-05-30 00:57 UTC, zhiweij1 approved these changes

2023-05-31 03:03 UTC, zhimingwang36 approved these changes
LGTM

2023-06-14 00:24 UTC, merged