[SYCLomatic] Support migration of thrust::set_symmetric_difference_by_key and thrust::set_symmetric_difference
oneapi-src/SYCLomatic pull request #985
Opened 2023-06-06 08:59 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2023-06-15 00:05 UTC, zhiweij1 requested changes

2023-06-15 00:05 UTC, zhiweij1 commented on clang/test/dpct/thrust-algo-part2.cu
> +  thrust::set_symmetric_difference_by_key(thrust::device, d_A_keys.begin(), d_A_keys.end(), d_B_keys.begin(), d_B_keys.end(), d_A_vals.begin(), d_B_vals.begin(), d_keys_result.begin(), d_vals_result.
```suggestion
  thrust::set_symmetric_difference_by_key(thrust::device, d_A_keys.begin(), d_A_keys.end(), d_B_keys.begin(), d_B_keys.end(), d_A_vals.begin(), d_B_vals.begin(), d_keys_result.begin(), d_vals_result.begin(), Compare());
```

2023-06-15 00:05 UTC, zhiweij1 commented on clang/test/dpct/thrust-algo-part2.cu
> +      thrust::set_symmetric_difference_by_key(d_A_keys.begin(), d_A_keys.end(), d_B_keys.begin(), d_B_keys.end(), d_A_vals.begin(), d_B_vals.begin(), d_keys_result.begin(), d_vals_result.begin(), Com
```suggestion
  thrust::set_symmetric_difference_by_key(d_A_keys.begin(), d_A_keys.end(), d_B_keys.begin(), d_B_keys.end(), d_A_vals.begin(), d_B_vals.begin(), d_keys_result.begin(), d_vals_result.begin(), Compare());
```

2023-06-15 00:05 UTC, zhiweij1 commented on clang/test/dpct/thrust-algo-part2.cu
> +          thrust::set_symmetric_difference_by_key(thrust::host, h_A_keys.begin(), h_A_keys.end(), h_B_keys.begin(), h_B_keys.end(), h_A_vals.begin(), h_B_vals.begin(), h_keys_result.begin(), h_vals_r
```suggestion
  thrust::set_symmetric_difference_by_key(thrust::host, h_A_keys.begin(), h_A_keys.end(), h_B_keys.begin(), h_B_keys.end(), h_A_vals.begin(), h_B_vals.begin(), h_keys_result.begin(), h_vals_result.begin());
```

2023-06-15 00:28 UTC, tomflinda commented on clang/test/dpct/thrust-algo-part2.cu
> +  thrust::set_symmetric_difference_by_key(thrust::device, d_A_keys.begin(), d_A_keys.end(), d_B_keys.begin(), d_B_keys.end(), d_A_vals.begin(), d_B_vals.begin(), d_keys_result.begin(), d_vals_result.
Updated

2023-06-15 00:28 UTC, tomflinda commented on clang/test/dpct/thrust-algo-part2.cu
> +          thrust::set_symmetric_difference_by_key(thrust::host, h_A_keys.begin(), h_A_keys.end(), h_B_keys.begin(), h_B_keys.end(), h_A_vals.begin(), h_B_vals.begin(), h_keys_result.begin(), h_vals_r
Updated

2023-06-15 00:31 UTC, zhiweij1 approved these changes

2023-06-29 00:28 UTC, zhimingwang36 approved these changes
LGTM

2023-07-04 00:13 UTC, merged